name: iEnvs
options:
  bundleIdPrefix: com.ienvs
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Automatic
    PRODUCT_NAME: iEnvs
    MARKETING_VERSION: "1.1.0"
    CURRENT_PROJECT_VERSION: "2503011150"

targets:
  iEnvs:
    type: application
    platform: macOS
    sources:
      - path: iEnvs
        excludes:
          - "**/*.md"
    settings:
      base:
        INFOPLIST_FILE: iEnvs/Info.plist
        CODE_SIGN_ENTITLEMENTS: iEnvs/iEnvs.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.ienvs.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        GENERATE_INFOPLIST_FILE: NO
    info:
      path: iEnvs/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
